import { id } from './id';
import Lang from './lang';

const languages: Lang[] = [
  { id: id('en'), name: 'English', flag: '🇬🇧' },
  { id: id('de'), name: 'Deutsch', flag: '🇩🇪' },
  { id: id('fr'), name: 'Français', flag: '🇫🇷' },
  { id: id('es'), name: 'Español', flag: '🇪🇸' },
  { id: id('it'), name: 'Italiano', flag: '🇮🇹' },
  { id: id('ru'), name: 'Русский', flag: '🇷🇺' },
  { id: id('zh'), name: '中文', flag: '🇨🇳' },
  { id: id('ja'), name: '日本語', flag: '🇯🇵' },
  { id: id('ko'), name: '한국어', flag: '🇰🇷' },
  { id: id('ar'), name: 'العربية', flag: '🇸🇦' },
  { id: id('pt'), name: 'Português', flag: '🇵🇹' },
  { id: id('hi'), name: 'हिन्दी', flag: '🇮🇳' },
  { id: id('bn'), name: 'বাংলা', flag: '🇧🇩' },
  { id: id('ur'), name: 'اردو', flag: '🇵🇰' },
  { id: id('tr'), name: 'Türkçe', flag: '🇹🇷' },
  { id: id('vi'), name: 'Tiếng Việt', flag: '🇻🇳' },
  { id: id('pl'), name: 'Polski', flag: '🇵🇱' },
  { id: id('uk'), name: 'Українська', flag: '🇺🇦' },
  { id: id('nl'), name: 'Nederlands', flag: '🇳🇱' },
  { id: id('sv'), name: 'Svenska', flag: '🇸🇪' },
  { id: id('no'), name: 'Norsk', flag: '🇳🇴' },
  { id: id('da'), name: 'Dansk', flag: '🇩🇰' },
  { id: id('fi'), name: 'Suomi', flag: '🇫🇮' },
  { id: id('cs'), name: 'Čeština', flag: '🇨🇿' },
  { id: id('el'), name: 'Ελληνικά', flag: '🇬🇷' },
  { id: id('hu'), name: 'Magyar', flag: '🇭🇺' },
  { id: id('ro'), name: 'Română', flag: '🇷🇴' },
  { id: id('sr'), name: 'Српски', flag: '🇷🇸' },
  { id: id('sk'), name: 'Slovenčina', flag: '🇸🇰' },
  { id: id('bg'), name: 'Български', flag: '🇧🇬' },
  { id: id('hr'), name: 'Hrvatski', flag: '🇭🇷' },
  { id: id('he'), name: 'עברית', flag: '🇮🇱' },
  { id: id('id'), name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { id: id('ms'), name: 'Bahasa Melayu', flag: '🇲🇾' },
  { id: id('th'), name: 'ไทย', flag: '🇹🇭' },
  { id: id('fa'), name: 'فارسی', flag: '🇮🇷' },
  { id: id('sw'), name: 'Kiswahili', flag: '🇰🇪' },
  { id: id('ta'), name: 'தமிழ்', flag: '🇱🇰' },
  { id: id('te'), name: 'తెలుగు', flag: '🇮🇳' },
  { id: id('ml'), name: 'മലയാളം', flag: '🇮🇳' },
  { id: id('kn'), name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { id: id('mr'), name: 'मराठी', flag: '🇮🇳' },
  { id: id('pa'), name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { id: id('gu'), name: 'ગુજરાતી', flag: '🇮🇳' },
  { id: id('am'), name: 'አማርኛ', flag: '🇪🇹' },
  { id: id('my'), name: 'မြန်မာစာ', flag: '🇲🇲' },
  { id: id('km'), name: 'ភាសាខ្មែរ', flag: '🇰🇭' },
  { id: id('lo'), name: 'ລາວ', flag: '🇱🇦' },
  { id: id('si'), name: 'සිංහල', flag: '🇱🇰' },
  { id: id('sl'), name: 'Slovenščina', flag: '🇸🇮' },
  { id: id('et'), name: 'Eesti', flag: '🇪🇪' },
  { id: id('lv'), name: 'Latviešu', flag: '🇱🇻' },
  { id: id('lt'), name: 'Lietuvių', flag: '🇱🇹' },
  { id: id('is'), name: 'Íslenska', flag: '🇮🇸' },
  { id: id('ga'), name: 'Gaeilge', flag: '🇮🇪' },
  { id: id('cy'), name: 'Cymraeg', flag: '🏴' },
  { id: id('mt'), name: 'Malti', flag: '🇲🇹' },
  { id: id('sq'), name: 'Shqip', flag: '🇦🇱' },
  { id: id('mk'), name: 'Македонски', flag: '🇲🇰' },
  { id: id('bs'), name: 'Bosanski', flag: '🇧🇦' },
  { id: id('az'), name: 'Azərbaycan', flag: '🇦🇿' },
  { id: id('ka'), name: 'ქართული', flag: '🇬🇪' },
  { id: id('hy'), name: 'Հայերեն', flag: '🇦🇲' },
  { id: id('mn'), name: 'Монгол', flag: '🇲🇳' },
  { id: id('uz'), name: 'Oʻzbekcha', flag: '🇺🇿' },
  { id: id('kk'), name: 'Қазақша', flag: '🇰🇿' },
  { id: id('tg'), name: 'Тоҷикӣ', flag: '🇹🇯' },
  { id: id('tk'), name: 'Türkmençe', flag: '🇹🇲' },
  { id: id('ky'), name: 'Кыргызча', flag: '🇰🇬' },
];

export default languages;