import {type Lang, type LangCode} from './Lang.ts';

const languages: Lang[] = [
  {code: 'en' as LangCode, name: 'English', flag: '🇬🇧'},
  {code: 'de' as LangCode, name: 'Deutsch', flag: '🇩🇪'},
  {code: 'fr' as LangCode, name: 'Français', flag: '🇫🇷'},
  {code: 'es' as LangCode, name: 'Español', flag: '🇪🇸'},
  {code: 'it' as LangCode, name: 'Italiano', flag: '🇮🇹'},
  {code: 'ru' as LangCode, name: 'Русский', flag: '🇷🇺'},
  {code: 'zh' as LangCode, name: '中文', flag: '🇨🇳'},
  {code: 'ja' as LangCode, name: '日本語', flag: '🇯🇵'},
  {code: 'ko' as LangCode, name: '한국어', flag: '🇰🇷'},
  {code: 'ar' as LangCode, name: 'العربية', flag: '🇸🇦'},
  {code: 'pt' as LangCode, name: 'Português', flag: '🇵🇹'},
  {code: 'hi' as LangCode, name: 'हिन्दी', flag: '🇮🇳'},
  {code: 'bn' as LangCode, name: 'বাংলা', flag: '🇧🇩'},
  {code: 'ur' as LangCode, name: 'اردو', flag: '🇵🇰'},
  {code: 'tr' as LangCode, name: 'Türkçe', flag: '🇹🇷'},
  {code: 'vi' as LangCode, name: 'Tiếng Việt', flag: '🇻🇳'},
  {code: 'pl' as LangCode, name: 'Polski', flag: '🇵🇱'},
  {code: 'uk' as LangCode, name: 'Українська', flag: '🇺🇦'},
  {code: 'nl' as LangCode, name: 'Nederlands', flag: '🇳🇱'},
  {code: 'sv' as LangCode, name: 'Svenska', flag: '🇸🇪'},
  {code: 'no' as LangCode, name: 'Norsk', flag: '🇳🇴'},
  {code: 'da' as LangCode, name: 'Dansk', flag: '🇩🇰'},
  {code: 'fi' as LangCode, name: 'Suomi', flag: '🇫🇮'},
  {code: 'cs' as LangCode, name: 'Čeština', flag: '🇨🇿'},
  {code: 'el' as LangCode, name: 'Ελληνικά', flag: '🇬🇷'},
  {code: 'hu' as LangCode, name: 'Magyar', flag: '🇭🇺'},
  {code: 'ro' as LangCode, name: 'Română', flag: '🇷🇴'},
  {code: 'sr' as LangCode, name: 'Српски', flag: '🇷🇸'},
  {code: 'sk' as LangCode, name: 'Slovenčina', flag: '🇸🇰'},
  {code: 'bg' as LangCode, name: 'Български', flag: '🇧🇬'},
  {code: 'hr' as LangCode, name: 'Hrvatski', flag: '🇭🇷'},
  {code: 'he' as LangCode, name: 'עברית', flag: '🇮🇱'},
  {code: 'id' as LangCode, name: 'Bahasa Indonesia', flag: '🇮🇩'},
  {code: 'ms' as LangCode, name: 'Bahasa Melayu', flag: '🇲🇾'},
  {code: 'th' as LangCode, name: 'ไทย', flag: '🇹🇭'},
  {code: 'fa' as LangCode, name: 'فارسی', flag: '🇮🇷'},
  {code: 'sw' as LangCode, name: 'Kiswahili', flag: '🇰🇪'},
  {code: 'ta' as LangCode, name: 'தமிழ்', flag: '🇱🇰'},
  {code: 'te' as LangCode, name: 'తెలుగు', flag: '🇮🇳'},
  {code: 'ml' as LangCode, name: 'മലയാളം', flag: '🇮🇳'},
  {code: 'kn' as LangCode, name: 'ಕನ್ನಡ', flag: '🇮🇳'},
  {code: 'mr' as LangCode, name: 'मराठी', flag: '🇮🇳'},
  {code: 'pa' as LangCode, name: 'ਪੰਜਾਬੀ', flag: '🇮🇳'},
  {code: 'gu' as LangCode, name: 'ગુજરાતી', flag: '🇮🇳'},
  {code: 'am' as LangCode, name: 'አማርኛ', flag: '🇪🇹'},
  {code: 'my' as LangCode, name: 'မြန်မာစာ', flag: '🇲🇲'},
  {code: 'km' as LangCode, name: 'ភាសាខ្មែរ', flag: '🇰🇭'},
  {code: 'lo' as LangCode, name: 'ລາວ', flag: '🇱🇦'},
  {code: 'si' as LangCode, name: 'සිංහල', flag: '🇱🇰'},
  {code: 'sl' as LangCode, name: 'Slovenščina', flag: '🇸🇮'},
  {code: 'et' as LangCode, name: 'Eesti', flag: '🇪🇪'},
  {code: 'lv' as LangCode, name: 'Latviešu', flag: '🇱🇻'},
  {code: 'lt' as LangCode, name: 'Lietuvių', flag: '🇱🇹'},
  {code: 'is' as LangCode, name: 'Íslenska', flag: '🇮🇸'},
  {code: 'ga' as LangCode, name: 'Gaeilge', flag: '🇮🇪'},
  {code: 'cy' as LangCode, name: 'Cymraeg', flag: '🏴'},
  {code: 'mt' as LangCode, name: 'Malti', flag: '🇲🇹'},
  {code: 'sq' as LangCode, name: 'Shqip', flag: '🇦🇱'},
  {code: 'mk' as LangCode, name: 'Македонски', flag: '🇲🇰'},
  {code: 'bs' as LangCode, name: 'Bosanski', flag: '🇧🇦'},
  {code: 'az' as LangCode, name: 'Azərbaycan', flag: '🇦🇿'},
  {code: 'ka' as LangCode, name: 'ქართული', flag: '🇬🇪'},
  {code: 'hy' as LangCode, name: 'Հայերեն', flag: '🇦🇲'},
  {code: 'mn' as LangCode, name: 'Монгол', flag: '🇲🇳'},
  {code: 'uz' as LangCode, name: 'Oʻzbekcha', flag: '🇺🇿'},
  {code: 'kk' as LangCode, name: 'Қазақша', flag: '🇰🇿'},
  {code: 'tg' as LangCode, name: 'Тоҷикӣ', flag: '🇹🇯'},
  {code: 'tk' as LangCode, name: 'Türkmençe', flag: '🇹🇲'},
  {code: 'ky' as LangCode, name: 'Кыргызча', flag: '🇰🇬'},
];

export default languages;
