import Lang from './lang';

const languages: Lang[] = [
  { code:'en',name: 'English', flag: '🇬🇧' },
  { code:'de',name: 'Deutsch', flag: '🇩🇪' },
  { code:'fr',name: 'Français', flag: '🇫🇷' },
  { code:'es',name: 'Español', flag: '🇪🇸' },
  { code:'it',name: 'Italiano', flag: '🇮🇹' },
  { code:'ru',name: 'Русский', flag: '🇷🇺' },
  { code:'zh',name: '中文', flag: '🇨🇳' },
  { code:'ja',name: '日本語', flag: '🇯🇵' },
  { code:'ko',name: '한국어', flag: '🇰🇷' },
  { code:'ar',name: 'العربية', flag: '🇸🇦' },
  { code:'pt',name: 'Português', flag: '🇵🇹' },
  { code:'hi',name: 'हिन्दी', flag: '🇮🇳' },
  { code:'bn',name: 'বাংলা', flag: '🇧🇩' },
  { code:'ur',name: 'اردو', flag: '🇵🇰' },
  { code:'tr',name: 'Türkçe', flag: '🇹🇷' },
  { code:'vi',name: 'Tiếng Việt', flag: '🇻🇳' },
  { code:'pl',name: 'Polski', flag: '🇵🇱' },
  { code:'uk',name: 'Українська', flag: '🇺🇦' },
  { code:'nl',name: 'Nederlands', flag: '🇳🇱' },
  { code:'sv',name: 'Svenska', flag: '🇸🇪' },
  { code:'no',name: 'Norsk', flag: '🇳🇴' },
  { code:'da',name: 'Dansk', flag: '🇩🇰' },
  { code:'fi',name: 'Suomi', flag: '🇫🇮' },
  { code:'cs',name: 'Čeština', flag: '🇨🇿' },
  { code:'el',name: 'Ελληνικά', flag: '🇬🇷' },
  { code:'hu',name: 'Magyar', flag: '🇭🇺' },
  { code:'ro',name: 'Română', flag: '🇷🇴' },
  { code:'sr',name: 'Српски', flag: '🇷🇸' },
  { code:'sk',name: 'Slovenčina', flag: '🇸🇰' },
  { code:'bg',name: 'Български', flag: '🇧🇬' },
  { code:'hr',name: 'Hrvatski', flag: '🇭🇷' },
  { code:'he',name: 'עברית', flag: '🇮🇱' },
  { code:'id',name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code:'ms',name: 'Bahasa Melayu', flag: '🇲🇾' },
  { code:'th',name: 'ไทย', flag: '🇹🇭' },
  { code:'fa',name: 'فارسی', flag: '🇮🇷' },
  { code:'sw',name: 'Kiswahili', flag: '🇰🇪' },
  { code:'ta',name: 'தமிழ்', flag: '🇱🇰' },
  { code:'te',name: 'తెలుగు', flag: '🇮🇳' },
  { code:'ml',name: 'മലയാളം', flag: '🇮🇳' },
  { code:'kn',name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code:'mr',name: 'मराठी', flag: '🇮🇳' },
  { code:'pa',name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code:'gu',name: 'ગુજરાતી', flag: '🇮🇳' },
  { code:'am',name: 'አማርኛ', flag: '🇪🇹' },
  { code:'my',name: 'မြန်မာစာ', flag: '🇲🇲' },
  { code:'km',name: 'ភាសាខ្មែរ', flag: '🇰🇭' },
  { code:'lo',name: 'ລາວ', flag: '🇱🇦' },
  { code:'si',name: 'සිංහල', flag: '🇱🇰' },
  { code:'sl',name: 'Slovenščina', flag: '🇸🇮' },
  { code:'et',name: 'Eesti', flag: '🇪🇪' },
  { code:'lv',name: 'Latviešu', flag: '🇱🇻' },
  { code:'lt',name: 'Lietuvių', flag: '🇱🇹' },
  { code:'is',name: 'Íslenska', flag: '🇮🇸' },
  { code:'ga',name: 'Gaeilge', flag: '🇮🇪' },
  { code:'cy',name: 'Cymraeg', flag: '🏴' },
  { code:'mt',name: 'Malti', flag: '🇲🇹' },
  { code:'sq',name: 'Shqip', flag: '🇦🇱' },
  { code:'mk',name: 'Македонски', flag: '🇲🇰' },
  { code:'bs',name: 'Bosanski', flag: '🇧🇦' },
  { code:'az',name: 'Azərbaycan', flag: '🇦🇿' },
  { code:'ka',name: 'ქართული', flag: '🇬🇪' },
  { code:'hy',name: 'Հայերեն', flag: '🇦🇲' },
  { code:'mn',name: 'Монгол', flag: '🇲🇳' },
  { code:'uz',name: 'Oʻzbekcha', flag: '🇺🇿' },
  { code:'kk',name: 'Қазақша', flag: '🇰🇿' },
  { code:'tg',name: 'Тоҷикӣ', flag: '🇹🇯' },
  { code:'tk',name: 'Türkmençe', flag: '🇹🇲' },
  { code:'ky',name: 'Кыргызча', flag: '🇰🇬' },
];

export default languages;