name: CLI Rest CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Ivy2 and SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Compile
        env:
          PGSQL_PASSWORD: ${{ secrets.PGSQL_PASSWORD }}
          PGSQL_HOST: ${{ env.PGSQL_HOST }}
        run: |
          cd services
          sbt clean test cliRest/assembly
