name: Build Scala backend

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

        
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: 'sbt'
    - name: build
      run: |
        cd scala
        sbt Universal/packageZipTarball
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    - name: deploy
      env:
        DEPLOY_DESTINATION: ${{ secrets.DEPLOY_DESTINATION }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo 1 > 1.txt
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no scala/edge-service/rest/target/universal/edge-service-rest-0.1.0-SNAPSHOT.tgz "$DEPLOY_DESTINATION"
        ssh -o StrictHostKeyChecking=no "$DEPLOY_HOST" "./memgrain.edge.rest.deploy.sh edge-service-rest-0.1.0-SNAPSHOT"
#    - name: upload dependency graph
#      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
